export const state = {
  selectedColor: 0x00ff00,
  savedId: "",
  isMouseDown: false,
  activeMouseButton: null,
  lastPlaceTime: 0,
  lastHit: null,
  isAlive: true,
  isSpectating: false,
  spectateIndex: 0,
  singlePlayer: false,
  playerList: [],
  playersState: {},
  otherPlayers: {},
  isCreatorMode: false,
  socket: "",
  camera: "",
  worldData: [],
  yVelocity: 0,
  gravity: -0.01,
  isOnGround: true,
  isSinglePlayer: true,
  enemies: [],
  move: { forward: false, back: false, left: false, right: false },
  renderer: {},
  playerName: "",
  roomId: "",
  jumpForce: 0.35,
  playerHealth: 100,
  isGameOver: false,
};
