export const state = {
  selectedColor: 0x00ff00,
  isMouseDown: false,
  activeMouseButton: null,
  lastPlaceTime: 0,
  lastHit: null,
  isAlive: true,
  isSpectating: false,
  spectateIndex: 0,
  playerList: [],
  playersState: {},
  otherPlayers: {},
  isCreatorMode: false,
  socket: "",
  camera: "",
  worldData: [],
  // yVelocity: 0,
  gravity: 9.81,
  isSinglePlayer: false,
  enemies: [],
  move: { forward: false, back: false, left: false, right: false, jump: true },
  renderer: {},
  playerName: "",
  playerId: "",
  roomId: "",
  jumpForce: 10,
  playerHealth: 100,
  isGameOver: false,
  isAdmin: false,
  adminId: "",
  compiledMap: null,
  compiledBodies: [],
  objects: [],
};
